DROP DATABASE IF EXISTS gocial CASCADE;
CREATE DATABASE IF NOT EXISTS gocial;
SET DATABASE = gocial;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL NOT NULL PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    username VARCHAR NOT NULL UNIQUE
);
